### PR TITLE
[R1] Add login page features

### PR DESCRIPTION
**Pull request by atangent**
# Summary of PR
Implemented the R1 Login features that were not already in boilerplate code from CI-Python Template
Created methods in `frontend.py` that ensure that:
- Email field or password field cannot be empty
- Email must follow RFC 5322 format
- Password must meet minimum complexity (at least 6 letters, one special char, one uppercase, one lowercase)

### CODE REVIEW

**Comment by atangent** [comment]
Looks like the build is failing on the regex on that one line of code. Let me look into that. Lmk if you have any ideas how to resolve it!

**Comment by SethDamiani** [comment]
Regex isn't my strong suit, but you could probably use this one I found online: 

`([!#-'*+/-9=?A-Z^-~-]+(\.[!#-'*+/-9=?A-Z^-~-]+)*|"([]!#-[^-~ \t]|(\\[\t -~]))+")@([!#-'*+/-9=?A-Z^-~-]+(\.[!#-'*+/-9=?A-Z^-~-]+)*|\[[\t -Z^-~]*])`

It seems to be the 'official' one.

**Comment by Chumingsun** [comment]
- The test case which is failing is due to the introduction of the check on e-mail formatting that you've introduced. There's a default test case that uses a wrongly formatted e-mail in the integration registration tests, which is why this is happening.
- I have already solved this issue in my PR, both in the test case as well as in the register and login, with the correct expression. Just remove these changes from your PR and we should be good to merge without conflicts.

**Comment by atangent** [comment]
Okay thank you. I've removed the email format checks (email is empty or email format does not meet RFC 5322) since @Chumingsun already did it in his PR. The **new summary of this PR** is that I added features in `frontend.py` ensuring:
- Password meets complexity requirements
- Password field is not empty

Build now passes! Looks good to merge now to me.

**Review by SethDamiani — APPROVED** [review]

**Comment by atangent** [comment]
Just did a quick fix on the `check_valid_password` function in `frontend.py`. Added a check for `char.isalnum()` before seeing if it's `char.isupper()` or `char.islower()`

This avoids a situation where we check for upper/lowercase on a special character, and getting an error

The rest of the file (`frontend.py`) is the same as last commit

**Pull request merged**
