### PR TITLE
R3 tests

### PR DESCRIPTION
**Pull request by atangent**
# Description

These are the tests I wrote for R3

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Pytest Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by atangent** [comment]
Fixed every broken thing. Updated the PR summary template as necessary.

**Review by SethDamiani — APPROVED** [review]
Looks good to me! Giving each form element its own ID is an interesting technique.

**Review by Chumingsun — APPROVED** [review]
Ready to merge. We should consider splitting tests into individual files next time.

**Comment by Kymed** [comment]
Looks good

**Pull request merged**
